from fastapi import APIRouter, Depends, HTTPException, status, Query
from fastapi.responses import FileResponse, StreamingResponse
from sqlalchemy.orm import Session
from typing import List
from io import BytesIO
import re

from app.core.database import get_db
from app.core.security import get_current_user
from app.models.user import User
from app.models.ai_system import AISystem
from app.models.document import Document, DocumentType, DocumentStatus
from app.schemas.document import (
    DocumentCreate,
    DocumentResponse,
    DocumentGenerateRequest,
    DocumentUpdateRequest,
)
from app.schemas.pagination import PaginatedResponse

# PDF generation
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_LEFT, TA_CENTER

router = APIRouter()


# Document templates for generation
DOCUMENT_TEMPLATES = {
    DocumentType.TECHNICAL_DOCUMENTATION: """
# Technical Documentation - {system_name}

## 1. General Description
**System Name:** {system_name}
**Version:** {version}
**Use Case:** {use_case}
**Sector:** {sector}

## 2. Intended Purpose
{description}

## 3. System Architecture
[Describe the overall architecture, components, and data flow]

## 4. Training Data
- Data sources used
- Data preprocessing steps
- Data quality measures

## 5. Model Information
- Algorithm/model type
- Training methodology
- Performance metrics

## 6. Input/Output Specifications
- Expected inputs
- Output format and interpretation

## 7. Limitations and Risks
- Known limitations
- Identified risks and mitigations

## 8. Human Oversight Measures
- Human-in-the-loop mechanisms
- Override capabilities

## 9. Logging and Monitoring
- What is logged
- Monitoring procedures

---
Generated by EU AI Act Compliance Tool
""",
    DocumentType.RISK_ASSESSMENT: """
# Risk Assessment Report - {system_name}

## Executive Summary
This document presents the risk assessment for {system_name}, an AI system used for {use_case}.

**Risk Level:** {risk_level}
**Assessment Date:** {date}

## 1. System Overview
{description}

## 2. Risk Classification
Based on EU AI Act criteria, this system is classified as **{risk_level}** risk.

### Classification Rationale
{classification_reasons}

## 3. Identified Risks

### 3.1 Data-Related Risks
- [ ] Data quality issues
- [ ] Bias in training data
- [ ] Privacy concerns

### 3.2 Model-Related Risks
- [ ] Accuracy limitations
- [ ] Robustness issues
- [ ] Explainability gaps

### 3.3 Deployment Risks
- [ ] Misuse potential
- [ ] Human oversight gaps
- [ ] Integration risks

## 4. Mitigation Measures
{recommendations}

## 5. Compliance Requirements
{requirements}

## 6. Next Steps
{next_steps}

---
Generated by EU AI Act Compliance Tool
""",
    DocumentType.CONFORMITY_DECLARATION: """
# EU Declaration of Conformity

## AI System Identification
**System Name:** {system_name}
**Version:** {version}
**Manufacturer/Provider:** {company_name}

## Declaration
We hereby declare that the AI system identified above has been designed and developed in conformity with the requirements of Regulation (EU) 2024/1689 (EU AI Act).

## Applicable Requirements
The following requirements have been addressed:

- [ ] Article 9 - Risk Management System
- [ ] Article 10 - Data and Data Governance
- [ ] Article 11 - Technical Documentation
- [ ] Article 12 - Record-keeping
- [ ] Article 13 - Transparency and Information
- [ ] Article 14 - Human Oversight
- [ ] Article 15 - Accuracy, Robustness, Cybersecurity

## Conformity Assessment
**Assessment Type:** Internal control (Annex VI)
**Date of Assessment:** {date}

## Responsible Person
**Name:** _______________
**Title:** _______________
**Date:** _______________
**Signature:** _______________

---
Generated by EU AI Act Compliance Tool
""",
}


@router.post("/", response_model=DocumentResponse, status_code=status.HTTP_201_CREATED)
def create_document(
    doc_data: DocumentCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new manual document.

    Unlike ``/generate``, this endpoint creates a document from user-provided
    content directly.

    Args:
        doc_data: ``DocumentCreate`` schema containing title, content,
            document_type, and ai_system_id.
        db: SQLAlchemy session (injected).
        current_user: Authenticated user (injected via JWT).

    Returns:
        DocumentResponse: The newly created document (HTTP 201).
    """
    document = Document(
        owner_id=current_user.id,
        title=doc_data.title,
        document_type=doc_data.document_type,
        ai_system_id=doc_data.ai_system_id,
        content=doc_data.content,
    )
    db.add(document)
    db.commit()
    db.refresh(document)
    return document


@router.get("/", response_model=PaginatedResponse[DocumentResponse])
def list_documents(
    page: int = Query(1, ge=1, description="Page number (1-indexed)"),
    limit: int = Query(50, ge=1, le=100, description="Items per page"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """List all documents for the current user with pagination.

    Args:
        page: 1-indexed page number.
        limit: Items per page (1–100).
        db: SQLAlchemy session (injected).
        current_user: Authenticated user (injected via JWT).

    Returns:
        PaginatedResponse[DocumentResponse]: Paginated document list.
    """
    base_query = db.query(Document).filter(Document.owner_id == current_user.id)
    total = base_query.count()
    offset = (page - 1) * limit

    documents = base_query.offset(offset).limit(limit).all()
    return PaginatedResponse(items=documents, total=total, page=page, limit=limit)


@router.get("/{document_id}", response_model=DocumentResponse)
def get_document(
    document_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Retrieve a specific document.

    Args:
        document_id: Primary-key of the document.
        db: SQLAlchemy session (injected).
        current_user: Authenticated user (injected via JWT).

    Returns:
        DocumentResponse: The requested document.

    Raises:
        HTTPException(404): If not found or not owned by the user.
    """
    document = (
        db.query(Document)
        .filter(Document.id == document_id, Document.owner_id == current_user.id)
        .first()
    )

    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Document not found"
        )
    return document

@router.put("/{document_id}", response_model=DocumentResponse)
def update_document(
    document_id: int,
    body: DocumentUpdateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Update a document's content.

    Only the ``content`` field can be modified through this endpoint.

    Args:
        document_id: Primary-key of the document to update.
        body: ``DocumentUpdateRequest`` containing the new markdown content.
        db: SQLAlchemy session (injected).
        current_user: Authenticated user (injected via JWT).

    Returns:
        DocumentResponse: The updated document.

    Raises:
        HTTPException(404): If not found or not owned by the user.
    """
    # Fetch document
    document = db.query(Document).filter(
        Document.id == document_id,
        Document.owner_id == current_user.id
    ).first()
    
    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Document not found"
        )
    
    # Update content
    document.content = body.content
    db.commit()
    db.refresh(document)
    
    return document

@router.post("/generate", response_model=DocumentResponse)
def generate_document(
    request: DocumentGenerateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Generate a compliance document using an LLM.

    Builds a document for an AI system using the system's latest risk
    assessment. If the LLM generation fails, it falls back to filling
    a static template.

    Args:
        request: ``DocumentGenerateRequest`` with ``ai_system_id`` and
            ``document_type``.
        db: SQLAlchemy session (injected).
        current_user: Authenticated user (injected via JWT).

    Returns:
        DocumentResponse: The generated document in a ``GENERATED`` state.

    Raises:
        HTTPException(404): If the AI system is not found.
        HTTPException(400): If no template is available for the requested type.
    """
    # Get the AI system
    ai_system = (
        db.query(AISystem)
        .filter(
            AISystem.id == request.ai_system_id, AISystem.owner_id == current_user.id
        )
        .first()
    )

    if not ai_system:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="AI system not found"
        )

    # Get template
    template = DOCUMENT_TEMPLATES.get(request.document_type)
    if not template:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"No template available for {request.document_type}",
        )

    # Get latest risk assessment if available
    from app.models.ai_system import RiskAssessment

    assessment = db.query(RiskAssessment).filter(
        RiskAssessment.ai_system_id == ai_system.id
    ).order_by(RiskAssessment.assessed_at.desc()).first()
    
    try:
        content = generate_compliance_narrative(
            document_type=request.document_type,
            ai_system=ai_system,
            risk_assessment=assessment,
            company_name=current_user.company_name
        )
    except Exception as e:
        import logging
        logger = logging.getLogger(__name__)
        logger.warning(f"LLM generation failed, falling back to template: {str(e)}")
        
        from datetime import datetime
        content = template.format(
            system_name=ai_system.name,
            version=ai_system.version or "1.0",
            use_case=ai_system.use_case or "Not specified",
            sector=ai_system.sector or "Not specified",
            description=ai_system.description or "No description provided",
            risk_level=ai_system.risk_level.value if ai_system.risk_level else "Not assessed",
            date=datetime.utcnow().strftime("%Y-%m-%d"),
            company_name=current_user.company_name or "Not specified",
            classification_reasons="See risk assessment details",
            recommendations="Based on risk assessment",
            requirements="See applicable requirements above",
            next_steps="Complete all checklist items"
        )

    # Create document
    document = Document(
        owner_id=current_user.id,
        ai_system_id=ai_system.id,
        title=f"{request.document_type.value.replace('_', ' ').title()} - {ai_system.name}",
        document_type=request.document_type,
        status=DocumentStatus.GENERATED,
        content=content,
    )
    db.add(document)
    db.commit()
    db.refresh(document)

    return document


@router.delete("/{document_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_document(
    document_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Delete a document permanently.

    Args:
        document_id: Primary-key of the document.
        db: SQLAlchemy session (injected).
        current_user: Authenticated user (injected via JWT).

    Raises:
        HTTPException(404): If not found or not owned by the user.
    """
    document = (
        db.query(Document)
        .filter(Document.id == document_id, Document.owner_id == current_user.id)
        .first()
    )

    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Document not found"
        )

    db.delete(document)
    db.commit()


@router.get("/{document_id}/pdf")
def export_document_pdf(
    document_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Export a document as a PDF file.
    
    Converts the stored markdown content to PDF via an external API.

    Args:
        document_id: Primary-key of the document.
        db: SQLAlchemy session (injected).
        current_user: Authenticated user (injected via JWT).

    Returns:
        StreamingResponse: PDF attachment (``application/pdf``).

    Raises:
        HTTPException(404): If the document is not found.
        HTTPException(400): If the document has no content.
        HTTPException(500): If the external PDF generation fails.

        - Content-Type: application/pdf
        - File starts with %PDF- magic bytes
        - File size > 1KB
    """
    # Retrieve the document
    document = db.query(Document).filter(
        Document.id == document_id,
        Document.owner_id == current_user.id
    ).first()
    
    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Document not found"
        )
    
    if not document.content:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Document has no content to export"
        )
    
    # Generate PDF
    pdf_buffer = BytesIO()
    
    # Create PDF document
    doc = SimpleDocTemplate(
        pdf_buffer,
        pagesize=A4,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=0.75*inch,
        bottomMargin=0.75*inch,
    )
    
    # Container for PDF elements
    story = []
    
    # Get styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor='#1f2937',
        spaceAfter=12,
        alignment=TA_CENTER,
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['BodyText'],
        fontSize=11,
        alignment=TA_LEFT,
        spaceAfter=12,
    )
    
    # Add title
    story.append(Paragraph(document.title, title_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Add metadata
    metadata_style = ParagraphStyle(
        'Metadata',
        parent=styles['Normal'],
        fontSize=9,
        textColor='#6b7280',
        spaceAfter=12,
    )
    story.append(Paragraph(f"<b>Document Type:</b> {document.document_type.value}", metadata_style))
    story.append(Paragraph(f"<b>Status:</b> {document.status.value}", metadata_style))
    story.append(Paragraph(f"<b>Created:</b> {document.created_at.strftime('%Y-%m-%d %H:%M:%S')}", metadata_style))
    story.append(Spacer(1, 0.3*inch))
    
    # Process content - split by lines and handle markdown-like formatting
    content_lines = document.content.split('\n')
    for line in content_lines:
        if not line.strip():
            story.append(Spacer(1, 0.1*inch))
        elif line.startswith('# '):
            # Heading 1
            heading_style = ParagraphStyle(
                'CustomHeading1',
                parent=styles['Heading1'],
                fontSize=16,
                textColor='#1f2937',
                spaceAfter=12,
                spaceBefore=12,
            )
            story.append(Paragraph(line.replace('# ', ''), heading_style))
        elif line.startswith('## '):
            # Heading 2
            heading_style = ParagraphStyle(
                'CustomHeading2',
                parent=styles['Heading2'],
                fontSize=13,
                textColor='#374151',
                spaceAfter=10,
                spaceBefore=10,
            )
            story.append(Paragraph(line.replace('## ', ''), heading_style))
        elif line.startswith('### '):
            # Heading 3
            heading_style = ParagraphStyle(
                'CustomHeading3',
                parent=styles['Heading3'],
                fontSize=11,
                textColor='#4b5563',
                spaceAfter=8,
                spaceBefore=8,
            )
            story.append(Paragraph(line.replace('### ', ''), heading_style))
        elif line.startswith('- '):
            # Bullet point
            story.append(Paragraph('• ' + line.replace('- ', ''), body_style))
        else:
            # Handle inline bold with regex
            processed_line = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', line.strip())
            story.append(Paragraph(processed_line, body_style))
    
    # Build PDF
    doc.build(story)
    
    # Get PDF bytes
    pdf_bytes = pdf_buffer.getvalue()
    
    # Verify PDF is valid (starts with %PDF- magic bytes)
    if not pdf_bytes.startswith(b'%PDF-'):
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="PDF generation failed - invalid PDF format"
        )
    
    # Verify PDF is larger than 1KB
    if len(pdf_bytes) < 1024:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="PDF generation failed - PDF too small"
        )
    
    # Return PDF response
    return StreamingResponse(
        BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{document.title}.pdf"'}
    )
