"""add ai_system_audit_logs table

Revision ID: a07332552936
Revises: 
Create Date: 2026-05-10 21:44:14.183048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07332552936'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'STARTER', 'GROWTH', 'SCALE', name='subscriptiontier'), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('ai_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('use_case', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('risk_level', sa.Enum('UNACCEPTABLE', 'HIGH', 'LIMITED', 'MINIMAL', name='risklevel'), nullable=True),
    sa.Column('compliance_status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'UNDER_REVIEW', 'COMPLIANT', 'NON_COMPLIANT', name='compliancestatus'), nullable=True),
    sa.Column('compliance_score', sa.Integer(), nullable=True),
    sa.Column('questionnaire_responses', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_systems_id'), 'ai_systems', ['id'], unique=False)
    op.create_table('ai_system_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_system_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_system_audit_logs_id'), 'ai_system_audit_logs', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('ai_system_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.Enum('TECHNICAL_DOCUMENTATION', 'RISK_ASSESSMENT', 'CONFORMITY_DECLARATION', 'DATA_GOVERNANCE', 'TRANSPARENCY_NOTICE', 'HUMAN_OVERSIGHT_PLAN', 'INCIDENT_REPORT', name='documenttype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'REVIEWED', 'APPROVED', 'ARCHIVED', name='documentstatus'), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_system_id', sa.Integer(), nullable=False),
    sa.Column('assessment_type', sa.String(length=100), nullable=True),
    sa.Column('risk_level', sa.Enum('UNACCEPTABLE', 'HIGH', 'LIMITED', 'MINIMAL', name='risklevel'), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('data_governance_score', sa.Integer(), nullable=True),
    sa.Column('transparency_score', sa.Integer(), nullable=True),
    sa.Column('human_oversight_score', sa.Integer(), nullable=True),
    sa.Column('robustness_score', sa.Integer(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_id'), 'risk_assessments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessments_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_ai_system_audit_logs_id'), table_name='ai_system_audit_logs')
    op.drop_table('ai_system_audit_logs')
    op.drop_index(op.f('ix_ai_systems_id'), table_name='ai_systems')
    op.drop_table('ai_systems')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
