import { useState } from 'react'
import { Bell, Check, Trash2, AlertTriangle, Bot, Newspaper, RefreshCw, HelpCircle } from 'lucide-react'
import { Tooltip } from '../components/AIPredictionBadge'

// ─── Types ────────────────────────────────────────────────────────────────────

type NotificationType = 'alert' | 'update' | 'ai' | 'news' | 'system_classified' | 'document_generated'

interface Notification {
  id: number
  notification_type: NotificationType
  title: string
  message: string
  is_read: boolean
  created_at: string
}

// TODO (help wanted): implement this API service object
// const notificationsApi = {
//   list: () => axios.get('/api/v1/notifications').then(r => r.data),
//   markRead: (ids: number[]) => axios.post('/api/v1/notifications/read', { ids }),
//   delete: (id: number) => axios.delete(`/api/v1/notifications/${id}`),
// }

const DUMMY_NOTIFICATIONS: Notification[] = [
  {
    id: 1,
    notification_type: 'alert',
    title: 'High-Risk System Detected',
    message: 'CV Screening AI was classified as High Risk under the EU AI Act. Immediate compliance action required.',
    is_read: false,
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    notification_type: 'ai',
    title: 'AI Classification Complete',
    message: 'AegisAI has finished classifying your "Customer Chatbot" system. Review the results and confidence score.',
    is_read: false,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    notification_type: 'document_generated',
    title: 'Document Ready',
    message: 'Technical Documentation for CV Screening AI has been generated and is ready to review.',
    is_read: true,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    notification_type: 'update',
    title: 'Compliance Score Updated',
    message: 'Your overall compliance score improved from 72% to 84% after completing the conformity checklist.',
    is_read: true,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 5,
    notification_type: 'news',
    title: 'EU AI Act Update',
    message: 'New guidance published on Article 52 transparency obligations for general-purpose AI models.',
    is_read: true,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// ─── Notification type config ─────────────────────────────────────────────────

interface TypeConfig {
  icon: React.ReactNode
  label: string
  badgeBg: string
  badgeText: string
  stripColor: string
  tooltipText: string
}

function getTypeConfig(type: NotificationType): TypeConfig {
  switch (type) {
    case 'alert':
      return {
        icon: <AlertTriangle className="w-4 h-4" />,
        label: 'Alert',
        badgeBg: 'bg-red-100',
        badgeText: 'text-red-700',
        stripColor: 'bg-red-500',
        tooltipText: 'Critical alert requiring immediate attention.',
      }
    case 'ai':
    case 'system_classified':
      return {
        icon: <Bot className="w-4 h-4" />,
        label: 'AI',
        badgeBg: 'bg-purple-100',
        badgeText: 'text-purple-700',
        stripColor: 'bg-purple-500',
        tooltipText: 'Generated by the AegisAI classification engine.',
      }
    case 'update':
      return {
        icon: <RefreshCw className="w-4 h-4" />,
        label: 'Update',
        badgeBg: 'bg-green-100',
        badgeText: 'text-green-700',
        stripColor: 'bg-green-500',
        tooltipText: 'A compliance status or score has been updated.',
      }
    case 'document_generated':
      return {
        icon: <RefreshCw className="w-4 h-4" />,
        label: 'Document',
        badgeBg: 'bg-blue-100',
        badgeText: 'text-blue-700',
        stripColor: 'bg-blue-500',
        tooltipText: 'An AI-generated compliance document is ready.',
      }
    case 'news':
    default:
      return {
        icon: <Newspaper className="w-4 h-4" />,
        label: 'News',
        badgeBg: 'bg-gray-100',
        badgeText: 'text-gray-600',
        stripColor: 'bg-gray-400',
        tooltipText: 'Regulatory news or EU AI Act updates.',
      }
  }
}

function timeAgo(iso: string): string {
  const s = Math.floor((Date.now() - new Date(iso).getTime()) / 1000)
  if (s < 60) return 'just now'
  const m = Math.floor(s / 60)
  if (m < 60) return `${m}m ago`
  const h = Math.floor(m / 60)
  if (h < 24) return `${h}h ago`
  return `${Math.floor(h / 24)}d ago`
}

// ─── UrgencyTypeBadge ─────────────────────────────────────────────────────────

interface UrgencyTypeBadgeProps {
  type: NotificationType
}

function UrgencyTypeBadge({ type }: UrgencyTypeBadgeProps) {
  const cfg = getTypeConfig(type)
  return (
    <Tooltip content={cfg.tooltipText}>
      <span
        className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-semibold border ${cfg.badgeBg} ${cfg.badgeText} border-transparent`}
      >
        {cfg.icon}
        {cfg.label}
      </span>
    </Tooltip>
  )
}

// ─── NotificationCard ─────────────────────────────────────────────────────────

interface NotificationCardProps {
  notification: Notification
  onDelete: (id: number) => void
  onMarkRead: (id: number) => void
}

function NotificationCard({ notification: n, onDelete, onMarkRead }: NotificationCardProps) {
  const cfg = getTypeConfig(n.notification_type)

  return (
    <div
      className={`bg-white rounded-xl border flex items-start gap-0 overflow-hidden transition-all ${
        !n.is_read
          ? 'border-primary-200 shadow-sm shadow-primary-50'
          : 'border-gray-200'
      }`}
    >
      {/* Left urgency strip */}
      <div className={`w-1 self-stretch flex-shrink-0 ${cfg.stripColor}`} />

      <div className="flex items-start gap-4 p-4 flex-1 min-w-0">
        {/* Unread dot */}
        <div className="flex-shrink-0 mt-1">
          <div
            className={`w-2 h-2 rounded-full ${!n.is_read ? 'bg-primary-500' : 'bg-gray-200'}`}
          />
        </div>

        {/* Content */}
        <div className="flex-1 min-w-0">
          <div className="flex items-start justify-between gap-3 flex-wrap">
            <div className="flex items-center gap-2 flex-wrap">
              <p
                className={`text-sm ${
                  !n.is_read ? 'font-semibold text-gray-900' : 'font-medium text-gray-700'
                }`}
              >
                {n.title}
              </p>
              <UrgencyTypeBadge type={n.notification_type} />
            </div>
            <span className="text-xs text-gray-400 flex-shrink-0">{timeAgo(n.created_at)}</span>
          </div>

          <p className="text-sm text-gray-600 mt-1 leading-relaxed">{n.message}</p>
        </div>

        {/* Actions */}
        <div className="flex items-center gap-1 flex-shrink-0">
          {!n.is_read && (
            <Tooltip content="Mark as read">
              <button
                onClick={() => onMarkRead(n.id)}
                className="p-1.5 text-gray-400 hover:text-primary-600 hover:bg-primary-50 rounded-lg transition-all"
                aria-label="Mark as read"
              >
                <Check className="w-4 h-4" />
              </button>
            </Tooltip>
          )}
          <Tooltip content="Delete notification">
            <button
              onClick={() => onDelete(n.id)}
              className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-all"
              aria-label="Delete notification"
            >
              <Trash2 className="w-4 h-4" />
            </button>
          </Tooltip>
        </div>
      </div>
    </div>
  )
}

// ─── Main Page ────────────────────────────────────────────────────────────────

const TYPE_FILTERS = [
  { value: '', label: 'All' },
  { value: 'alert', label: 'Alerts' },
  { value: 'ai', label: 'AI' },
  { value: 'update', label: 'Updates' },
  { value: 'news', label: 'News' },
]

export default function Notifications() {
  // TODO (help wanted): replace dummy data with real query
  // const { data: notifications = [] } = useQuery({ queryKey: ['notifications'], queryFn: notificationsApi.list })
  const [notifications, setNotifications] = useState<Notification[]>(DUMMY_NOTIFICATIONS)
  const [typeFilter, setTypeFilter] = useState('')

  const handleDelete = (id: number) => {
    setNotifications((prev) => prev.filter((n) => n.id !== id))
  }

  const handleMarkRead = (id: number) => {
    setNotifications((prev) =>
      prev.map((n) => (n.id === id ? { ...n, is_read: true } : n))
    )
  }

  const handleMarkAllRead = () => {
    setNotifications((prev) => prev.map((n) => ({ ...n, is_read: true })))
  }

  const filtered = notifications.filter((n) => {
    if (!typeFilter) return true
    const cfg = getTypeConfig(n.notification_type)
    return cfg.label.toLowerCase() === typeFilter
  })

  const unreadCount = notifications.filter((n) => !n.is_read).length

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Notifications</h1>
          <p className="text-gray-600 mt-1">Your recent compliance and system events</p>
        </div>
        {unreadCount > 0 && (
          <button
            onClick={handleMarkAllRead}
            className="flex items-center gap-2 px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 rounded-lg border border-gray-200 transition-all"
          >
            <Check className="w-4 h-4" />
            Mark all read
            <span className="ml-1 text-xs bg-primary-100 text-primary-700 px-1.5 py-0.5 rounded-full font-medium">
              {unreadCount}
            </span>
          </button>
        )}
      </div>

      {/* Legend + filter row */}
      <div className="flex items-center justify-between gap-4 flex-wrap">
        {/* Type filter pills */}
        <div className="flex items-center gap-2 flex-wrap">
          {TYPE_FILTERS.map((f) => (
            <button
              key={f.value}
              onClick={() => setTypeFilter(f.value)}
              className={`px-3 py-1.5 text-xs font-medium rounded-full border transition-all ${
                typeFilter === f.value
                  ? 'bg-primary-600 text-white border-primary-600'
                  : 'bg-white text-gray-600 border-gray-200 hover:border-primary-300 hover:text-primary-600'
              }`}
            >
              {f.label}
            </button>
          ))}
        </div>

        {/* Legend */}
        <div className="flex items-center gap-3 flex-wrap">
          <Tooltip content="Each notification type has a distinct color strip and badge so you can quickly identify its urgency.">
            <span className="flex items-center gap-1 text-xs text-gray-400 cursor-help">
              <HelpCircle className="w-3.5 h-3.5" />
              Color legend
            </span>
          </Tooltip>
          {(['alert', 'ai', 'update', 'news'] as NotificationType[]).map((t) => {
            const c = getTypeConfig(t)
            return (
              <span key={t} className="flex items-center gap-1.5 text-xs text-gray-500">
                <span className={`w-2 h-2 rounded-full ${c.stripColor}`} />
                {c.label}
              </span>
            )
          })}
        </div>
      </div>

      {/* Notification list */}
      {filtered.length === 0 ? (
        <div className="text-center py-12 bg-white rounded-xl border border-gray-200">
          <Bell className="w-16 h-16 mx-auto mb-4 text-gray-300" />
          <h3 className="text-lg font-medium text-gray-900">No notifications</h3>
          <p className="text-gray-500 mt-1">
            {typeFilter ? 'Try a different filter' : "You're all caught up."}
          </p>
        </div>
      ) : (
        <div className="space-y-2">
          {filtered.map((n) => (
            <NotificationCard
              key={n.id}
              notification={n}
              onDelete={handleDelete}
              onMarkRead={handleMarkRead}
            />
          ))}
        </div>
      )}
    </div>
  )
}
